include:
  - local: '.gitlab/ci/*.yml'
  - project: 'core-utils/gitlab-ci-yml-templates'
    file: 'templates/stages.yml'
    ref: master

variables:
  PROJECT_TYPE: 'ms'
  PROJECT_NAME: 'pact-consumer-example-for-typescript'
  PROJECT_COMPONENT: 'web'
  ORGANIZATION: 'gear-tech-excellence'
  DOMAIN: 'qraft'
  OWNER: 'qraft'

# Default and mainly used stages at Manomano
stages: !reference [.stages]

yarn_test:
  stage: ci:test
  script:
    - yarn test

test-contract-generate:
  stage: ci:test
  script:
    - yarn test

test-contract-publish:
  stage: ci:test
  needs:
    - job: test-contract-generate
  script:
    - make install-pact-cli
    - make show-broker-url
    - npx --yes absolute-version
    # - yarn publish:contracts
    - >
      ./pact/bin/pact-broker publish \
      "./pact/pacts" \
      --consumer-app-version="$(npx --yes absolute-version)" \
      --auto-detect-version-properties \
      --broker-base-url=${PACT_BROKER_URL} \
      --build-url="${CI_PIPELINE_URL:-no-pipeline-url}" \
      --verbose
